# Generated by Django 5.1.7 on 2025-04-02 04:57

import borrow.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0003_alter_borrowedbook_borrowed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='borrowed_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='return_date',
            field=models.DateTimeField(blank=True, default=borrow.models.BorrowedBook.default_return_date, null=True),
        ),
    ]
